[tool.poetry]
name = "autostack"
version = "0.1.0"
description = ""
authors = ["Kolena Engineering <eng@kolena.com>"]
readme = "README.md"
include = ["ui/dist/*", "ui/dist/assets/*"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
fastapi = "^0.112.2"
pandas = "^2.2.2"
uvicorn = "^0.30.6"
duckdb = "^1.0.0"
coolname = "^2.2.0"
pyarrow = "^17.0.0"
tqdm = "^4.66.5"
python-multipart = "^0.0.9"
loguru = "^0.7.2"
tenacity = "^9.0.0"
# TODO: these client libraries should be arranged into extras that are installed as needed (imports are lazy)
openai = "^1.43.0"
ollama = "^0.3.2"
anthropic = "^0.34.1"
cohere = "^5.9.0"
google-generativeai = "^0.7.2"
transformers = "^4.44.2"
torch = "^2.4.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
pytest = "^8.3.2"

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
