name: AutoStack
on:
  push:
    branches:
      - trunk
  pull_request:
    paths:
      - "*"
      - ".github/workflows/autostack.yml"

jobs:
  setup:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run pre-commit
        run: poetry run pre-commit run -a

  unit-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run unit tests
        run: poetry run pytest -v tests/unit
