name: AutoArena
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  autoarena-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache  # some jobs were failing due to disk space
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - name: Update dependencies
        run: poetry update
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: poetry install
      - name: Run pre-commit
        run: poetry run pre-commit run -a
      - name: Run unit tests
        run: poetry run pytest -v tests/unit
      - name: Run integration tests
        run: poetry run pytest -v tests/integration
