name: AutoArena
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - name: Setup environment
        run: uv venv --python ${{ matrix.python_version }} && source .venv/bin/activate
      - name: Install dependencies
        run: uv pip install --all-extras -r pyproject.toml
      - name: Run pre-commit
        run: uvx pre-commit run -a

  test:
    runs-on: ubuntu-latest
    needs: ui-build  # requires built frontend assets
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - name: Setup environment
        run: uv venv --python ${{ matrix.python_version }} && source .venv/bin/activate
      - name: Install dependencies
        run: uv pip install --all-extras -r pyproject.toml
      - name: Run unit tests
        run: uv run pytest -vv --cov-report term --cov-report xml:coverage.xml --cov autoarena --cov-append tests/unit
      - uses: actions/download-artifact@v4
        with:
          name: ui-build
          path: "./ui/dist"
      - name: Run integration tests
        run: uv run pytest -vv --cov-report term --cov-report xml:coverage.xml --cov autoarena --cov-append tests/integration
