name: AutoArena
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  autoarena-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache  # some jobs were failing due to disk space
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - uses: astral-sh/setup-uv@v2
      - name: Setup environment
        run: uv venv --python ${{ matrix.python_version }} && source .venv/bin/activate
      - name: Install dependencies
        run: uv pip install --all-extras -r pyproject.toml
      - name: Run pre-commit
        run: uvx pre-commit run -a
      - name: Run unit tests
        run: uv run pytest -vv --cov-report term --cov-report xml:coverage.xml --cov autoarena --cov-append tests/unit
      - name: Run integration tests
        run: uv run pytest -vv --cov-report term --cov-report xml:coverage.xml --cov autoarena --cov-append tests/integration
