name: Changelog

on:
  push:
    branches:
      - gh/changelog

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        run: git log $(git describe --tags --abbrev=0)..HEAD --oneline > CHANGELOG.md

      - name: Print the changelog
        run: cat CHANGELOG.md
