name: Frontend
on:
  push:
    branches:
      - trunk
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

env:
  NODE_VERSION: 20.11.1

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "./frontend/yarn.lock"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run linting
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "./frontend/yarn.lock"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run build
        run: yarn build

  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "./frontend/yarn.lock"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
