name: Release

on:
  push:
    tags:
      - "*"
    branches:
      - gh/automated-release

jobs:
  release:
    name: Build and publish release of kolena Python package and documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - name: Update dependencies
        run: poetry update
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Run pre-commit
        run: poetry run pre-commit run -a
      - name: Update package version to PEP 440-compliant production release tag
        run: poetry version $(git describe --tags --abbrev=0)
      - name: Run build script to build UI and bundle into Python tarball
        run: ./scripts/build.sh
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
